const tintColorLight = '#8bacff';
const tintColorDark = '#8bacff';

export default {
  light: {
    text: '#040a2f',
    background: '#e2e3ff',
    tint: tintColorLight,
    tabIconDefault: '#a3a8d5',
    tabIconSelected: tintColorLight,
    primary: '#8bacff',
    primaryDim: '#006cfb',
    primaryContainer: '#759eff',
    secondary: '#cad6fd',
    tertiary: '#ffc565',
    surface: '#fbf8ff',
    surfaceContainerLow: '#e2e3ff',
    surfaceContainer: '#d7d9ff',
    surfaceContainerHigh: '#cccefc',
    surfaceContainerHighest: '#c2c4f9',
    surfaceBright: '#fbf8ff',
    onSurface: '#040a2f',
    onSurfaceVariant: '#4d527a',
    outlineVariant: 'rgba(63, 69, 108, 0.15)',
    success: '#2ECC71',
    error: '#ff716c',
  },
  dark: {
    text: '#e2e3ff',
    background: '#040a2f',
    tint: tintColorDark,
    tabIconDefault: '#a3a8d5',
    tabIconSelected: tintColorDark,
    primary: '#8bacff',
    primaryDim: '#006cfb',
    primaryContainer: '#759eff',
    secondary: '#cad6fd',
    tertiary: '#ffc565',
    surface: '#040a2f',
    surfaceContainerLow: '#080e38',
    surfaceContainer: '#0d1542',
    surfaceContainerHigh: '#121a4c',
    surfaceContainerHighest: '#182056',
    surfaceBright: '#1d2660',
    onSurface: '#e2e3ff',
    onSurfaceVariant: '#a3a8d5',
    outlineVariant: 'rgba(63, 73, 157, 0.15)',
    success: '#2ECC71',
    error: '#ff716c',
  },
};
