export const STRINGS = {
  common: {
    loading: 'Loading...',
    error: 'Something went wrong',
    retry: 'Retry',
    cancel: 'Cancel',
    save: 'Save',
    edit: 'Edit',
    delete: 'Delete',
    back: 'Back',
    next: 'Next',
    done: 'Done',
  },
  auth: {
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account? ",
    hasAccount: 'Already have an account? ',
  },
  home: {
    title: 'Learning Paths',
    recentActivity: 'Recent Activity',
    continueLearning: 'Continue Learning',
    recommended: 'Recommended for You',
    allTopics: 'All Topics',
    completed: 'Completed',
    inProgress: 'In Progress',
    notStarted: 'Not Started',
    startLearning: 'Start Learning',
    continueCourse: 'Continue',
    viewAll: 'View All',
  },
  profile: {
    title: 'Profile',
    editProfile: 'Edit Profile',
    settings: 'Settings',
    about: 'About',
    help: 'Help & Support',
    darkMode: 'Dark Mode',
    notifications: 'Notifications',
    language: 'Language',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service',
    logout: 'Logout',
    deleteAccount: 'Delete Account',
    changePhoto: 'Change Photo',
    name: 'Name',
    email: 'Email',
    bio: 'Bio',
    joinDate: 'Member since',
    learningStats: 'Learning Stats',
    coursesCompleted: 'Courses Completed',
    streak: 'Day Streak',
    totalXP: 'Total XP',
  },
  about: {
    title: 'About',
    appName: 'Gamified Learning App',
    version: 'Version 1.0.0',
    description: 'An engaging learning platform that makes education fun and interactive through gamification.',
    features: [
      'Interactive lessons',
      'Track your progress',
      'Earn achievements',
      'Learn at your own pace',
    ],
    developer: 'Developed with ❤️',
  },
  errors: {
    network: 'Network error. Please check your connection.',
    invalidEmail: 'Please enter a valid email address',
    invalidPassword: 'Password must be at least 6 characters',
    passwordsDontMatch: "Passwords don't match",
    requiredField: 'This field is required',
    somethingWentWrong: 'Something went wrong. Please try again.',
  },
};
